KML_KEYWORD( KML_NAME,		"<name>" )
KML_KEYWORD( KML_FOLDER,	"<Folder>" )
KML_KEYWORD( KML_FOLDER2,	"</Folder>" )
KML_KEYWORD( KML_PLACEMARK,	"<Placemark>" )
KML_KEYWORD( KML_PLACEMARK2,"</Placemark>" )
KML_KEYWORD( KML_DESCR,		"<description>" )
KML_KEYWORD( KML_STYLE_URL,	"<styleUrl>" )
KML_KEYWORD( KML_STYLE_ID,	"<Style id=\"" )
KML_KEYWORD( KML_STYLEMAP_ID, "<StyleMap id=\"" )
KML_KEYWORD( KML_HREF,		"<href>" )
//KML_KEYWORD( KML_LONGITUDE,	"<longitude>" )
//KML_KEYWORD( KML_LATITUDE,	"<latitude>" )
KML_KEYWORD( KML_COORDINATES,	"<coordinates>" )
